### ISSUE TITLE
Small (but important) typo in README

### ISSUE THREAD

**Issue by ckx** [ret2src/kde-plasma-solarized#1]
Thanks for taking the time to make Plasma Solarized themes. I'm enjoying them both.

Quick typo you can fix in the README under installation:

```
$ wget https://raw.githubusercontent.com/ret2src/kde-plasma-solarized/main/BreezeSolarizedLight.colors -O ~/.local/share/color-schemes/BreezeSolarizedDark.colors
```

The above line should probably read:

```
$ wget https://raw.githubusercontent.com/ret2src/kde-plasma-solarized/main/BreezeSolarizedLight.colors -O ~/.local/share/color-schemes/BreezeSolarizedLight.colors
```

**Comment by ret2src** [comment]
Thank you for bringing this issue to my attention!
It should be fixed now :-)

**Comment by ret2src** [comment]
Thank you for bringing this issue to my attention!
It should be fixed now :-)

I'm really glad you're enjoying my Solarized themes!
