### ISSUE TITLE
Bad visibility in konsole

### ISSUE THREAD

**Issue by Dejweed** [ret2src/kde-plasma-solarized#2]
Hello!

I'm using Solarized dark in Konsole. My zsh autosuggestions are invisible because they are the same color as the background. They are perfectly visible in the light theme.

![image](https://github.com/ret2src/kde-plasma-solarized/assets/65261588/d655c5df-a0eb-4f47-858d-8453a4299969)

**Comment by ret2src** [comment]
Hi, thank you for reporting this issue!

I just looked into both color schemes and the funny thing is that they use their respective background color in exactly the same way, i.e. the same variables are set to the background color (look for "253,246,227" in the light version and "0,43,54" in the dark version).

If you want to find out which variable affects the color of your autosuggestion, you could try to progressively set the different variables that currently have the value "0,43,54" to something such as "255,0,0" (red) until your autosuggestion color changes to red. Once found, let me know which variable is responsible and we can look into changing the color, if it doesn't affect too much of the rest of the UI.

That said, I'm not sure if my theme or your ZSH prompt is responsible for the visibility problems. Can you revert to the default Breeze colorscheme and check if your autosuggestions are visible there?

**Comment by Dejweed** [comment]
Oh my bad, upon closer inspection it appears that Konsole colors are not supplied by this theme. So my issue is related to the color scheme that comes preinstalled with Konsole. Thank you for your quick response.
